### PR TITLE
Create settings.js

### PR DESCRIPTION
**Pull request by 1proprogrammerchant**
settings built in javascript from the json

### CODE REVIEW

**Comment by christianpaquin** [comment]
Can you explain the purpose of this PR, @1proprogrammerchant?

**Comment by 1proprogrammerchant** [comment]
its a parse from the settings.json turned into javascript

**Comment by 1proprogrammerchant** [comment]
> Can you explain the purpose of this PR, @1proprogrammerchant?

and I also want to keep parsing just to see how far this can go remember its an open source doc so I also want to make people see new ways of coding such as switching from one language to another to see which one runs the code faster. If that's ok with you

**Comment by christianpaquin** [comment]
This is a sample project to illustrate the use of the U-Prove technology, so we want to keep the code simple and well-scoped. Thank you for your submission but it doesn't look like a good fit for our goals.

**Comment by 1proprogrammerchant** [comment]
alright my friend you're welcome

**Pull request closed without merging**
